language: rust
rust: stable

cache:
  directories:
  - target

before_deploy:
- cargo build --release
- zip -9 akua-$TRAVIS_TAG-$TRAVIS_OS_NAME.zip ./target/release/akua

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  file: akua-$TRAVIS_TAG-$TRAVIS_OS_NAME.zip
  on:
    tags: true
